name: Build Windows Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow psutil

      - name: Build with PyInstaller using spec
        run: |
          pyinstaller GreenSoftwareMonitor.spec

      - name: Upload Windows executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: GreenSoftwareMonitor
          path: dist/GreenSoftwareMonitor/GreenSoftwareMonitor.exe

